package com.dream.dw.dao;

import com.dream.dw.model.LikeRecord;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    long countByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    int deleteByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    int insert(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    int insertSelective(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    List<LikeRecord> selectByExample(LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LikeRecord record, @Param("example") LikeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_like_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LikeRecord record, @Param("example") LikeRecordExample example);
}