package com.dream.dw.dao;

import com.dream.dw.model.TravelNote;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    long countByExample(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int deleteByExample(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int insert(TravelNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int insertSelective(TravelNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    List<TravelNote> selectByExampleWithBLOBs(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    List<TravelNote> selectByExample(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TravelNote record, @Param("example") TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TravelNote record, @Param("example") TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_travel_note
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TravelNote record, @Param("example") TravelNoteExample example);
}