# Spring profiles
spring:
  # Data source
  datasource:
    name: demo1
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dw?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 10
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat

# Mybatis
mybatis:
  typeAliasesPackage: com.dream.dw.dao
  mapperLocations: classpath*:mapping/*Mapper.xml

#fastdfs
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list: 192.168.192.129:22122


