package com.dream.dw.dao;

import com.dream.dw.model.CollectRecord;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    long countByExample(CollectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    int deleteByExample(CollectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    int insert(CollectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    int insertSelective(CollectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    List<CollectRecord> selectByExample(CollectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CollectRecord record, @Param("example") CollectRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dw_collect_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CollectRecord record, @Param("example") CollectRecordExample example);
}