package com.dream.dw.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dw_travel_note
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TravelNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.note_id
     *
     * @mbg.generated
     */
    private Long noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.browser_count
     *
     * @mbg.generated
     */
    private Long browserCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.collect_count
     *
     * @mbg.generated
     */
    private Long collectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.like_count
     *
     * @mbg.generated
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.cover_image_key
     *
     * @mbg.generated
     */
    private String coverImageKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.bg_music_key
     *
     * @mbg.generated
     */
    private String bgMusicKey;

    /**
     * Database Column Remarks:
     *   0: normal, 1: drafting
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   Travel note content in json format.
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_travel_note.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.id
     *
     * @return the value of t_dw_travel_note.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.id
     *
     * @param id the value for t_dw_travel_note.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.user_id
     *
     * @return the value of t_dw_travel_note.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.user_id
     *
     * @param userId the value for t_dw_travel_note.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.note_id
     *
     * @return the value of t_dw_travel_note.note_id
     *
     * @mbg.generated
     */
    public Long getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.note_id
     *
     * @param noteId the value for t_dw_travel_note.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.title
     *
     * @return the value of t_dw_travel_note.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.title
     *
     * @param title the value for t_dw_travel_note.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.browser_count
     *
     * @return the value of t_dw_travel_note.browser_count
     *
     * @mbg.generated
     */
    public Long getBrowserCount() {
        return browserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.browser_count
     *
     * @param browserCount the value for t_dw_travel_note.browser_count
     *
     * @mbg.generated
     */
    public void setBrowserCount(Long browserCount) {
        this.browserCount = browserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.collect_count
     *
     * @return the value of t_dw_travel_note.collect_count
     *
     * @mbg.generated
     */
    public Long getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.collect_count
     *
     * @param collectCount the value for t_dw_travel_note.collect_count
     *
     * @mbg.generated
     */
    public void setCollectCount(Long collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.like_count
     *
     * @return the value of t_dw_travel_note.like_count
     *
     * @mbg.generated
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.like_count
     *
     * @param likeCount the value for t_dw_travel_note.like_count
     *
     * @mbg.generated
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.time
     *
     * @return the value of t_dw_travel_note.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.time
     *
     * @param time the value for t_dw_travel_note.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.location
     *
     * @return the value of t_dw_travel_note.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.location
     *
     * @param location the value for t_dw_travel_note.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.cover_image_key
     *
     * @return the value of t_dw_travel_note.cover_image_key
     *
     * @mbg.generated
     */
    public String getCoverImageKey() {
        return coverImageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.cover_image_key
     *
     * @param coverImageKey the value for t_dw_travel_note.cover_image_key
     *
     * @mbg.generated
     */
    public void setCoverImageKey(String coverImageKey) {
        this.coverImageKey = coverImageKey == null ? null : coverImageKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.bg_music_key
     *
     * @return the value of t_dw_travel_note.bg_music_key
     *
     * @mbg.generated
     */
    public String getBgMusicKey() {
        return bgMusicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.bg_music_key
     *
     * @param bgMusicKey the value for t_dw_travel_note.bg_music_key
     *
     * @mbg.generated
     */
    public void setBgMusicKey(String bgMusicKey) {
        this.bgMusicKey = bgMusicKey == null ? null : bgMusicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.status
     *
     * @return the value of t_dw_travel_note.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.status
     *
     * @param status the value for t_dw_travel_note.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.create_time
     *
     * @return the value of t_dw_travel_note.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.create_time
     *
     * @param createTime the value for t_dw_travel_note.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.update_time
     *
     * @return the value of t_dw_travel_note.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.update_time
     *
     * @param updateTime the value for t_dw_travel_note.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_travel_note.content
     *
     * @return the value of t_dw_travel_note.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_travel_note.content
     *
     * @param content the value for t_dw_travel_note.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}