package com.dream.dw.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dw_collect_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CollectRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_collect_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_collect_record.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_collect_record.note_id
     *
     * @mbg.generated
     */
    private Long noteId;

    /**
     * Database Column Remarks:
     *   0: normal, 1: deleted
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_collect_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dw_collect_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_collect_record.id
     *
     * @return the value of t_dw_collect_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_collect_record.id
     *
     * @param id the value for t_dw_collect_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_collect_record.user_id
     *
     * @return the value of t_dw_collect_record.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_collect_record.user_id
     *
     * @param userId the value for t_dw_collect_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_collect_record.note_id
     *
     * @return the value of t_dw_collect_record.note_id
     *
     * @mbg.generated
     */
    public Long getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_collect_record.note_id
     *
     * @param noteId the value for t_dw_collect_record.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_collect_record.status
     *
     * @return the value of t_dw_collect_record.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_collect_record.status
     *
     * @param status the value for t_dw_collect_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dw_collect_record.create_time
     *
     * @return the value of t_dw_collect_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dw_collect_record.create_time
     *
     * @param createTime the value for t_dw_collect_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}